# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_database.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1001, 611)
        Dialog.setStyleSheet(_fromUtf8("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);"))
        self.gridLayout_12 = QtGui.QGridLayout(Dialog)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.scrollArea_3 = QtGui.QScrollArea(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 308, 264))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_11 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_11.addWidget(self.label_11, 0, 0, 1, 1)
        self.peak_table = QtGui.QTableWidget(self.scrollAreaWidgetContents_3)
        self.peak_table.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.peak_table.setObjectName(_fromUtf8("peak_table"))
        self.peak_table.setColumnCount(0)
        self.peak_table.setRowCount(0)
        self.gridLayout_11.addWidget(self.peak_table, 1, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_12.addWidget(self.scrollArea_3, 1, 2, 1, 1)
        self.scrollArea = QtGui.QScrollArea(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 539))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.molecules_table = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.molecules_table.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.molecules_table.setObjectName(_fromUtf8("molecules_table"))
        self.molecules_table.setColumnCount(0)
        self.molecules_table.setRowCount(0)
        self.gridLayout.addWidget(self.molecules_table, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_12.addWidget(self.scrollArea, 0, 1, 2, 1)
        self.scrollArea_2 = QtGui.QScrollArea(Dialog)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 308, 265))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.toolButton = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.toolButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.toolButton_3 = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.toolButton_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.horizontalLayout_2.addWidget(self.toolButton_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.info_table = QtGui.QTableWidget(self.scrollAreaWidgetContents_2)
        self.info_table.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.info_table.setObjectName(_fromUtf8("info_table"))
        self.info_table.setColumnCount(0)
        self.info_table.setRowCount(0)
        self.gridLayout_2.addWidget(self.info_table, 1, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_12.addWidget(self.scrollArea_2, 0, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setContentsMargins(-1, -1, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.known_chk = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.known_chk.sizePolicy().hasHeightForWidth())
        self.known_chk.setSizePolicy(sizePolicy)
        self.known_chk.setStyleSheet(_fromUtf8(""))
        self.known_chk.setAutoExclusive(False)
        self.known_chk.setObjectName(_fromUtf8("known_chk"))
        self.gridLayout_10.addWidget(self.known_chk, 1, 1, 1, 1)
        self.artifact_chk = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.artifact_chk.sizePolicy().hasHeightForWidth())
        self.artifact_chk.setSizePolicy(sizePolicy)
        self.artifact_chk.setStyleSheet(_fromUtf8(""))
        self.artifact_chk.setObjectName(_fromUtf8("artifact_chk"))
        self.gridLayout_10.addWidget(self.artifact_chk, 2, 1, 1, 1)
        self.experiment_chk = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.experiment_chk.sizePolicy().hasHeightForWidth())
        self.experiment_chk.setSizePolicy(sizePolicy)
        self.experiment_chk.setStyleSheet(_fromUtf8(""))
        self.experiment_chk.setObjectName(_fromUtf8("experiment_chk"))
        self.gridLayout_10.addWidget(self.experiment_chk, 0, 1, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.gridLayout_10)
        self.label = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.mhz_chk = QtGui.QCheckBox(self.groupBox_3)
        self.mhz_chk.setStyleSheet(_fromUtf8(""))
        self.mhz_chk.setObjectName(_fromUtf8("mhz_chk"))
        self.gridLayout_9.addWidget(self.mhz_chk, 0, 0, 1, 1)
        self.ghz_chk = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ghz_chk.sizePolicy().hasHeightForWidth())
        self.ghz_chk.setSizePolicy(sizePolicy)
        self.ghz_chk.setStyleSheet(_fromUtf8(""))
        self.ghz_chk.setObjectName(_fromUtf8("ghz_chk"))
        self.gridLayout_9.addWidget(self.ghz_chk, 2, 0, 1, 1)
        self.cm1_chk = QtGui.QCheckBox(self.groupBox_3)
        self.cm1_chk.setStyleSheet(_fromUtf8(""))
        self.cm1_chk.setObjectName(_fromUtf8("cm1_chk"))
        self.gridLayout_9.addWidget(self.cm1_chk, 3, 0, 1, 1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.gridLayout_9)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.temp_min_spinbx = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_min_spinbx.sizePolicy().hasHeightForWidth())
        self.temp_min_spinbx.setSizePolicy(sizePolicy)
        self.temp_min_spinbx.setObjectName(_fromUtf8("temp_min_spinbx"))
        self.gridLayout_3.addWidget(self.temp_min_spinbx, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.temp_max_spinbx = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_max_spinbx.sizePolicy().hasHeightForWidth())
        self.temp_max_spinbx.setSizePolicy(sizePolicy)
        self.temp_max_spinbx.setObjectName(_fromUtf8("temp_max_spinbx"))
        self.gridLayout_4.addWidget(self.temp_max_spinbx, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.composition_exactly_rdo = QtGui.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.composition_exactly_rdo.setFont(font)
        self.composition_exactly_rdo.setObjectName(_fromUtf8("composition_exactly_rdo"))
        self.gridLayout_7.addWidget(self.composition_exactly_rdo, 1, 0, 1, 1)
        self.composition_all_rdio = QtGui.QRadioButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.composition_all_rdio.sizePolicy().hasHeightForWidth())
        self.composition_all_rdio.setSizePolicy(sizePolicy)
        self.composition_all_rdio.setMinimumSize(QtCore.QSize(100, 0))
        self.composition_all_rdio.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.composition_all_rdio.setFont(font)
        self.composition_all_rdio.setObjectName(_fromUtf8("composition_all_rdio"))
        self.gridLayout_7.addWidget(self.composition_all_rdio, 0, 0, 1, 1)
        self.composition_has_rdio = QtGui.QRadioButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.composition_has_rdio.sizePolicy().hasHeightForWidth())
        self.composition_has_rdio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.composition_has_rdio.setFont(font)
        self.composition_has_rdio.setObjectName(_fromUtf8("composition_has_rdio"))
        self.gridLayout_7.addWidget(self.composition_has_rdio, 0, 1, 1, 1)
        self.composition_nothave_rdio = QtGui.QRadioButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.composition_nothave_rdio.setFont(font)
        self.composition_nothave_rdio.setObjectName(_fromUtf8("composition_nothave_rdio"))
        self.gridLayout_7.addWidget(self.composition_nothave_rdio, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.composition_txt = QtGui.QLineEdit(self.groupBox_3)
        self.composition_txt.setObjectName(_fromUtf8("composition_txt"))
        self.horizontalLayout_3.addWidget(self.composition_txt)
        self.composition_btn = QtGui.QToolButton(self.groupBox_3)
        self.composition_btn.setObjectName(_fromUtf8("composition_btn"))
        self.horizontalLayout_3.addWidget(self.composition_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.verticalLayout_3)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.dicharge_chk = QtGui.QCheckBox(self.groupBox_3)
        self.dicharge_chk.setObjectName(_fromUtf8("dicharge_chk"))
        self.gridLayout_8.addWidget(self.dicharge_chk, 0, 0, 1, 1)
        self.stable_chk = QtGui.QCheckBox(self.groupBox_3)
        self.stable_chk.setObjectName(_fromUtf8("stable_chk"))
        self.gridLayout_8.addWidget(self.stable_chk, 1, 0, 1, 1)
        self.heated_nozzle_chk = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heated_nozzle_chk.sizePolicy().hasHeightForWidth())
        self.heated_nozzle_chk.setSizePolicy(sizePolicy)
        self.heated_nozzle_chk.setObjectName(_fromUtf8("heated_nozzle_chk"))
        self.gridLayout_8.addWidget(self.heated_nozzle_chk, 0, 1, 1, 1)
        self.laser_ablation_chk = QtGui.QCheckBox(self.groupBox_3)
        self.laser_ablation_chk.setObjectName(_fromUtf8("laser_ablation_chk"))
        self.gridLayout_8.addWidget(self.laser_ablation_chk, 1, 1, 1, 1)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.gridLayout_8)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_10)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.isotope_chk = QtGui.QCheckBox(self.groupBox_3)
        self.isotope_chk.setObjectName(_fromUtf8("isotope_chk"))
        self.gridLayout_6.addWidget(self.isotope_chk, 0, 0, 1, 1)
        self.vibrational_chk = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vibrational_chk.sizePolicy().hasHeightForWidth())
        self.vibrational_chk.setSizePolicy(sizePolicy)
        self.vibrational_chk.setObjectName(_fromUtf8("vibrational_chk"))
        self.gridLayout_6.addWidget(self.vibrational_chk, 1, 0, 1, 1)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.gridLayout_6)
        self.gridLayout_5.addLayout(self.formLayout, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.reset_btn = QtGui.QPushButton(self.groupBox_3)
        self.reset_btn.setObjectName(_fromUtf8("reset_btn"))
        self.horizontalLayout_7.addWidget(self.reset_btn)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.filter_btn = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_btn.sizePolicy().hasHeightForWidth())
        self.filter_btn.setSizePolicy(sizePolicy)
        self.filter_btn.setStyleSheet(_fromUtf8("background-color: rgb(1, 133, 116);"))
        self.filter_btn.setObjectName(_fromUtf8("filter_btn"))
        self.horizontalLayout_7.addWidget(self.filter_btn)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 0, 0, 2, 1)
        self.frame_2 = QtGui.QFrame(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet(_fromUtf8("background-color: rgb(32, 32, 32);"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.back_btn = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        self.back_btn.setObjectName(_fromUtf8("back_btn"))
        self.horizontalLayout_4.addWidget(self.back_btn)
        self.advanced_btn = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.advanced_btn.sizePolicy().hasHeightForWidth())
        self.advanced_btn.setSizePolicy(sizePolicy)
        self.advanced_btn.setStyleSheet(_fromUtf8("background-color: rgb(1, 133, 116);"))
        self.advanced_btn.setObjectName(_fromUtf8("advanced_btn"))
        self.horizontalLayout_4.addWidget(self.advanced_btn)
        self.gridLayout_12.addWidget(self.frame_2, 2, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_11.setText(_translate("Dialog", "Peak Information", None))
        self.label_5.setText(_translate("Dialog", "Molecule Entries", None))
        self.label_6.setText(_translate("Dialog", "Info", None))
        self.toolButton.setText(_translate("Dialog", "Edit", None))
        self.toolButton_3.setText(_translate("Dialog", "Save", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Filter", None))
        self.label_2.setText(_translate("Dialog", "Category", None))
        self.known_chk.setText(_translate("Dialog", "Known", None))
        self.artifact_chk.setText(_translate("Dialog", "Artifact", None))
        self.experiment_chk.setText(_translate("Dialog", "Experiment", None))
        self.label.setText(_translate("Dialog", "Frequency", None))
        self.mhz_chk.setText(_translate("Dialog", "MHz", None))
        self.ghz_chk.setText(_translate("Dialog", "GHz", None))
        self.cm1_chk.setText(_translate("Dialog", "cm -1", None))
        self.label_3.setText(_translate("Dialog", "Temperature (K)", None))
        self.groupBox.setTitle(_translate("Dialog", "Min", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Max", None))
        self.label_7.setText(_translate("Dialog", "Composition", None))
        self.composition_exactly_rdo.setText(_translate("Dialog", "Is exactly", None))
        self.composition_all_rdio.setText(_translate("Dialog", "All", None))
        self.composition_has_rdio.setText(_translate("Dialog", "Has", None))
        self.composition_nothave_rdio.setText(_translate("Dialog", "Does not have", None))
        self.composition_txt.setText(_translate("Dialog", "--", None))
        self.composition_btn.setText(_translate("Dialog", "...", None))
        self.label_9.setText(_translate("Dialog", "Experiment Type", None))
        self.dicharge_chk.setText(_translate("Dialog", "Discharge", None))
        self.stable_chk.setText(_translate("Dialog", "Stable", None))
        self.heated_nozzle_chk.setText(_translate("Dialog", "Heated Nozzle", None))
        self.laser_ablation_chk.setText(_translate("Dialog", "Laser Ablation", None))
        self.label_10.setText(_translate("Dialog", "Other", None))
        self.isotope_chk.setText(_translate("Dialog", "isotopes", None))
        self.vibrational_chk.setText(_translate("Dialog", "vibrational", None))
        self.reset_btn.setText(_translate("Dialog", "Reset", None))
        self.filter_btn.setText(_translate("Dialog", "Filter Results", None))
        self.back_btn.setText(_translate("Dialog", "Back to Main Menu", None))
        self.advanced_btn.setText(_translate("Dialog", "Advanced ...", None))

