# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importsingle.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_importsingle_frame(object):
    def setupUi(self, importsingle_frame):
        importsingle_frame.setObjectName(_fromUtf8("importsingle_frame"))
        importsingle_frame.resize(1032, 681)
        importsingle_frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        importsingle_frame.setAutoFillBackground(False)
        importsingle_frame.setStyleSheet(_fromUtf8("background-color: rgb(53, 53, 53);"))
        self.title_lbl = QtGui.QLabel(importsingle_frame)
        self.title_lbl.setGeometry(QtCore.QRect(70, 50, 419, 75))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Small Fonts"))
        font.setPointSize(13)
        self.title_lbl.setFont(font)
        self.title_lbl.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.title_lbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.title_lbl.setFrameShadow(QtGui.QFrame.Plain)
        self.title_lbl.setLineWidth(0)
        self.title_lbl.setObjectName(_fromUtf8("title_lbl"))
        self.next_lbl = QtGui.QLabel(importsingle_frame)
        self.next_lbl.setGeometry(QtCore.QRect(749, 541, 251, 75))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("8514oem"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.next_lbl.setFont(font)
        self.next_lbl.setAutoFillBackground(False)
        self.next_lbl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.next_lbl.setFrameShape(QtGui.QFrame.Panel)
        self.next_lbl.setFrameShadow(QtGui.QFrame.Raised)
        self.next_lbl.setLineWidth(6)
        self.next_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.next_lbl.setOpenExternalLinks(False)
        self.next_lbl.setObjectName(_fromUtf8("next_lbl"))
        self.back_lbl = QtGui.QLabel(importsingle_frame)
        self.back_lbl.setGeometry(QtCore.QRect(59, 541, 251, 75))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("8514oem"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.back_lbl.setFont(font)
        self.back_lbl.setAutoFillBackground(False)
        self.back_lbl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.back_lbl.setFrameShape(QtGui.QFrame.Panel)
        self.back_lbl.setFrameShadow(QtGui.QFrame.Raised)
        self.back_lbl.setLineWidth(6)
        self.back_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.back_lbl.setOpenExternalLinks(False)
        self.back_lbl.setObjectName(_fromUtf8("back_lbl"))
        self.logo = QtGui.QLabel(importsingle_frame)
        self.logo.setGeometry(QtCore.QRect(810, 50, 191, 61))
        self.logo.setAutoFillBackground(False)
        self.logo.setFrameShape(QtGui.QFrame.NoFrame)
        self.logo.setText(_fromUtf8(""))
        self.logo.setPixmap(QtGui.QPixmap(_fromUtf8("../../../resources/specdata_logo.png")))
        self.logo.setScaledContents(True)
        self.logo.setObjectName(_fromUtf8("logo"))
        self.frame = QtGui.QFrame(importsingle_frame)
        self.frame.setGeometry(QtCore.QRect(59, 121, 941, 401))
        self.frame.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(5)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.selectfile_txt = QtGui.QPlainTextEdit(self.frame)
        self.selectfile_txt.setGeometry(QtCore.QRect(200, 30, 541, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        self.selectfile_txt.setFont(font)
        self.selectfile_txt.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.selectfile_txt.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.selectfile_txt.setFrameShape(QtGui.QFrame.Panel)
        self.selectfile_txt.setFrameShadow(QtGui.QFrame.Raised)
        self.selectfile_txt.setLineWidth(5)
        self.selectfile_txt.setObjectName(_fromUtf8("selectfile_txt"))
        self.selectfile_btn = QtGui.QPushButton(self.frame)
        self.selectfile_btn.setGeometry(QtCore.QRect(730, 30, 61, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.selectfile_btn.sizePolicy().hasHeightForWidth())
        self.selectfile_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectfile_btn.setFont(font)
        self.selectfile_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectfile_btn.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 220);"))
        self.selectfile_btn.setAutoDefault(True)
        self.selectfile_btn.setObjectName(_fromUtf8("selectfile_btn"))
        self.name_txt = QtGui.QPlainTextEdit(self.frame)
        self.name_txt.setGeometry(QtCore.QRect(200, 110, 591, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        self.name_txt.setFont(font)
        self.name_txt.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.name_txt.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.name_txt.setFrameShape(QtGui.QFrame.Panel)
        self.name_txt.setFrameShadow(QtGui.QFrame.Raised)
        self.name_txt.setLineWidth(5)
        self.name_txt.setObjectName(_fromUtf8("name_txt"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 200, 281, 95))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.known_rbtn = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.known_rbtn.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.known_rbtn.setObjectName(_fromUtf8("known_rbtn"))
        self.verticalLayout_4.addWidget(self.known_rbtn)
        self.experiment_rbtn = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.experiment_rbtn.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.experiment_rbtn.setObjectName(_fromUtf8("experiment_rbtn"))
        self.verticalLayout_4.addWidget(self.experiment_rbtn)
        self.artifact_btn = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.artifact_btn.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.artifact_btn.setObjectName(_fromUtf8("artifact_btn"))
        self.verticalLayout_4.addWidget(self.artifact_btn)
        self.selectfile_lbl = QtGui.QLabel(self.frame)
        self.selectfile_lbl.setGeometry(QtCore.QRect(40, 30, 82, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Small Fonts"))
        font.setPointSize(9)
        self.selectfile_lbl.setFont(font)
        self.selectfile_lbl.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.selectfile_lbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.selectfile_lbl.setFrameShadow(QtGui.QFrame.Plain)
        self.selectfile_lbl.setLineWidth(0)
        self.selectfile_lbl.setObjectName(_fromUtf8("selectfile_lbl"))
        self.name_lbl = QtGui.QLabel(self.frame)
        self.name_lbl.setGeometry(QtCore.QRect(40, 100, 140, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Small Fonts"))
        font.setPointSize(9)
        self.name_lbl.setFont(font)
        self.name_lbl.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.name_lbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.name_lbl.setFrameShadow(QtGui.QFrame.Plain)
        self.name_lbl.setLineWidth(0)
        self.name_lbl.setObjectName(_fromUtf8("name_lbl"))
        self.category_lbl = QtGui.QLabel(self.frame)
        self.category_lbl.setGeometry(QtCore.QRect(40, 190, 130, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Small Fonts"))
        font.setPointSize(9)
        self.category_lbl.setFont(font)
        self.category_lbl.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.category_lbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.category_lbl.setFrameShadow(QtGui.QFrame.Plain)
        self.category_lbl.setLineWidth(0)
        self.category_lbl.setObjectName(_fromUtf8("category_lbl"))
        self.error_lbl = QtGui.QLabel(self.frame)
        self.error_lbl.setGeometry(QtCore.QRect(40, 310, 881, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("8514oem"))
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.error_lbl.setFont(font)
        self.error_lbl.setStyleSheet(_fromUtf8("color: rgb(255, 1, 1);\n"
""))
        self.error_lbl.setText(_fromUtf8(""))
        self.error_lbl.setWordWrap(True)
        self.error_lbl.setObjectName(_fromUtf8("error_lbl"))
        self.selectfile_lbl.raise_()
        self.selectfile_txt.raise_()
        self.name_txt.raise_()
        self.verticalLayoutWidget.raise_()
        self.selectfile_lbl.raise_()
        self.selectfile_lbl.raise_()
        self.name_lbl.raise_()
        self.category_lbl.raise_()
        self.selectfile_btn.raise_()
        self.error_lbl.raise_()
        self.title_lbl.raise_()
        self.frame.raise_()
        self.logo.raise_()
        self.selectfile_txt.raise_()
        self.next_lbl.raise_()
        self.back_lbl.raise_()

        self.retranslateUi(importsingle_frame)
        QtCore.QMetaObject.connectSlotsByName(importsingle_frame)

    def retranslateUi(self, importsingle_frame):
        importsingle_frame.setWindowTitle(_translate("importsingle_frame", "Dialog", None))
        self.title_lbl.setText(_translate("importsingle_frame", "Import Single File", None))
        self.next_lbl.setText(_translate("importsingle_frame", "Next", None))
        self.back_lbl.setText(_translate("importsingle_frame", "Back", None))
        self.selectfile_txt.setPlainText(_translate("importsingle_frame", "C://", None))
        self.selectfile_btn.setText(_translate("importsingle_frame", "...", None))
        self.known_rbtn.setText(_translate("importsingle_frame", "Known", None))
        self.experiment_rbtn.setText(_translate("importsingle_frame", "Experiment", None))
        self.artifact_btn.setText(_translate("importsingle_frame", "Artifact", None))
        self.selectfile_lbl.setText(_translate("importsingle_frame", "Select file", None))
        self.name_lbl.setText(_translate("importsingle_frame", "Enter entry name", None))
        self.category_lbl.setText(_translate("importsingle_frame", "Select category", None))

