# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importsingle.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_importsingle_form(object):
    def setupUi(self, importsingle_form):
        importsingle_form.setObjectName(_fromUtf8("importsingle_form"))
        importsingle_form.resize(1032, 681)
        importsingle_form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        importsingle_form.setAutoFillBackground(False)
        importsingle_form.setStyleSheet(_fromUtf8("background-color: rgb(0, 117, 135);"))
        self.title_lbl = QtGui.QLabel(importsingle_form)
        self.title_lbl.setGeometry(QtCore.QRect(70, 50, 419, 75))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Small Fonts"))
        font.setPointSize(13)
        self.title_lbl.setFont(font)
        self.title_lbl.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.title_lbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.title_lbl.setFrameShadow(QtGui.QFrame.Plain)
        self.title_lbl.setLineWidth(0)
        self.title_lbl.setObjectName(_fromUtf8("title_lbl"))
        self.new_lbl = QtGui.QLabel(importsingle_form)
        self.new_lbl.setGeometry(QtCore.QRect(749, 541, 251, 75))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("8514oem"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.new_lbl.setFont(font)
        self.new_lbl.setAutoFillBackground(False)
        self.new_lbl.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.new_lbl.setFrameShape(QtGui.QFrame.Panel)
        self.new_lbl.setFrameShadow(QtGui.QFrame.Raised)
        self.new_lbl.setLineWidth(6)
        self.new_lbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.new_lbl.setOpenExternalLinks(False)
        self.new_lbl.setObjectName(_fromUtf8("new_lbl"))
        self.new_lbl_2 = QtGui.QLabel(importsingle_form)
        self.new_lbl_2.setGeometry(QtCore.QRect(59, 541, 251, 75))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("8514oem"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.new_lbl_2.setFont(font)
        self.new_lbl_2.setAutoFillBackground(False)
        self.new_lbl_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.new_lbl_2.setFrameShape(QtGui.QFrame.Panel)
        self.new_lbl_2.setFrameShadow(QtGui.QFrame.Raised)
        self.new_lbl_2.setLineWidth(6)
        self.new_lbl_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.new_lbl_2.setOpenExternalLinks(False)
        self.new_lbl_2.setObjectName(_fromUtf8("new_lbl_2"))
        self.label = QtGui.QLabel(importsingle_form)
        self.label.setGeometry(QtCore.QRect(810, 50, 191, 61))
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("../resources/specdata_logo.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.frame = QtGui.QFrame(importsingle_form)
        self.frame.setGeometry(QtCore.QRect(59, 121, 941, 401))
        self.frame.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(5)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.name_txt = QtGui.QTextEdit(importsingle_form)
        self.name_txt.setGeometry(QtCore.QRect(229, 268, 529, 41))
        self.name_txt.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.name_txt.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);"))
        self.name_txt.setFrameShape(QtGui.QFrame.Panel)
        self.name_txt.setFrameShadow(QtGui.QFrame.Raised)
        self.name_txt.setLineWidth(4)
        self.name_txt.setObjectName(_fromUtf8("name_txt"))
        self.name_lbl = QtGui.QLabel(importsingle_form)
        self.name_lbl.setGeometry(QtCore.QRect(80, 268, 140, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Small Fonts"))
        font.setPointSize(9)
        self.name_lbl.setFont(font)
        self.name_lbl.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.name_lbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.name_lbl.setFrameShadow(QtGui.QFrame.Plain)
        self.name_lbl.setLineWidth(0)
        self.name_lbl.setObjectName(_fromUtf8("name_lbl"))
        self.selectfile_lbl_2 = QtGui.QLabel(importsingle_form)
        self.selectfile_lbl_2.setGeometry(QtCore.QRect(80, 371, 130, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Small Fonts"))
        font.setPointSize(9)
        self.selectfile_lbl_2.setFont(font)
        self.selectfile_lbl_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.selectfile_lbl_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.selectfile_lbl_2.setFrameShadow(QtGui.QFrame.Plain)
        self.selectfile_lbl_2.setLineWidth(0)
        self.selectfile_lbl_2.setObjectName(_fromUtf8("selectfile_lbl_2"))
        self.verticalLayoutWidget = QtGui.QWidget(importsingle_form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(229, 371, 119, 95))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.known_rbtn = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.known_rbtn.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.known_rbtn.setObjectName(_fromUtf8("known_rbtn"))
        self.verticalLayout_4.addWidget(self.known_rbtn)
        self.experiment_rbtn = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.experiment_rbtn.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.experiment_rbtn.setObjectName(_fromUtf8("experiment_rbtn"))
        self.verticalLayout_4.addWidget(self.experiment_rbtn)
        self.artifact_btn = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.artifact_btn.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.artifact_btn.setObjectName(_fromUtf8("artifact_btn"))
        self.verticalLayout_4.addWidget(self.artifact_btn)
        self.selectfile_txt = QtGui.QTextEdit(importsingle_form)
        self.selectfile_txt.setGeometry(QtCore.QRect(230, 160, 531, 41))
        self.selectfile_txt.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.selectfile_txt.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 0);"))
        self.selectfile_txt.setFrameShape(QtGui.QFrame.Panel)
        self.selectfile_txt.setFrameShadow(QtGui.QFrame.Raised)
        self.selectfile_txt.setLineWidth(4)
        self.selectfile_txt.setObjectName(_fromUtf8("selectfile_txt"))
        self.selectfile_lbl = QtGui.QLabel(importsingle_form)
        self.selectfile_lbl.setGeometry(QtCore.QRect(80, 152, 82, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Small Fonts"))
        font.setPointSize(9)
        self.selectfile_lbl.setFont(font)
        self.selectfile_lbl.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.selectfile_lbl.setFrameShape(QtGui.QFrame.NoFrame)
        self.selectfile_lbl.setFrameShadow(QtGui.QFrame.Plain)
        self.selectfile_lbl.setLineWidth(0)
        self.selectfile_lbl.setObjectName(_fromUtf8("selectfile_lbl"))
        self.selectfile_btn = QtGui.QPushButton(importsingle_form)
        self.selectfile_btn.setGeometry(QtCore.QRect(710, 160, 51, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.selectfile_btn.sizePolicy().hasHeightForWidth())
        self.selectfile_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectfile_btn.setFont(font)
        self.selectfile_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selectfile_btn.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 220);"))
        self.selectfile_btn.setAutoDefault(True)
        self.selectfile_btn.setObjectName(_fromUtf8("selectfile_btn"))
        self.title_lbl.raise_()
        self.frame.raise_()
        self.new_lbl.raise_()
        self.new_lbl_2.raise_()
        self.selectfile_btn.raise_()
        self.label.raise_()

        self.retranslateUi(importsingle_form)
        QtCore.QMetaObject.connectSlotsByName(importsingle_form)

    def retranslateUi(self, importsingle_form):
        importsingle_form.setWindowTitle(_translate("importsingle_form", "Dialog", None))
        self.title_lbl.setText(_translate("importsingle_form", "Import Single File", None))
        self.new_lbl.setText(_translate("importsingle_form", "Next", None))
        self.new_lbl_2.setText(_translate("importsingle_form", "Back", None))
        self.name_lbl.setText(_translate("importsingle_form", "Enter entry name", None))
        self.selectfile_lbl_2.setText(_translate("importsingle_form", "Select category", None))
        self.known_rbtn.setText(_translate("importsingle_form", "Known", None))
        self.experiment_rbtn.setText(_translate("importsingle_form", "Experiment", None))
        self.artifact_btn.setText(_translate("importsingle_form", "Artifact", None))
        self.selectfile_lbl.setText(_translate("importsingle_form", "Select file", None))
        self.selectfile_btn.setText(_translate("importsingle_form", "...", None))

